services:
  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    ports:
      - "5432:5432"
    networks:
      - kong-network
    restart: on-failure
    environment:
      - KONG_PG_HOST=host.docker.internal
      - KONG_PG_PASSWORD=
      - KONG_PG_USER=irfan.baig

  kong:
    image: kong:latest
    container_name: kong
    restart: always
    # command: "kong migrations bootstrap"
    depends_on:
      - kong-migration
      - redis
    ports:
      - "8000:8000" # 8000 and 8443 are the ports to the API gateway
      - "8001:8001" # 8001 and 8444 are the ports to the Admin API
      - "8443:8443"
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=host.docker.internal
      - KONG_PG_PORT=5432
      - KONG_PG_PASSWORD=
      - KONG_PG_USER=irfan.baig
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
      - KONG_RATE_LIMITING_POLICY=redis
      - KONG_REDIS_HOST=redis
      - KONG_REDIS_PORT=6379
      #    - KONG_ADMIN_LISTEN: '0.0.0.0:8001, 0.0.0.0:8444 ssl'
      - KONG_CLUSTER_LISTEN=0.0.0.0:7946
      - KONG_CLUSTER_ADVERTISE=kong:7946 # Or Docker host IP if not using Docker network DNS
      - KONG_UNTRUSTED_LUA=on
      - KONG_UNTRUSTED_LUA_SANDBOX_REQUIRES=off
      - KONG_UNTRUSTED_LUA_SANDBOX_MEMORY=500m
#    volumes:
#      - ./nginx_kong.lua:/usr/local/share/lua/5.1/kong/plugins/custom_plugin/nginx_kong.lua
    #        - ./nginx_kong.lua:/usr/local/kong/plugins/nginx_kong.lua
    #      - ./kong.yml:/etc/kong/kong.yml  # Mount the Kong configuration file
    networks:
      - kong-network

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - kong-network
    volumes:
      - redis_data:/data


  httpbin:
    container_name: httpbin
    image: kennethreitz/httpbin
    ports:
      - "8090:80"
    networks:
      - kong-network

networks:
  kong-network:

volumes:
  redis_data:
